name: Docs

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    # The maximum number of minutes to let a workflow run
    # before GitHub automatically cancels it. Default: 360
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          virtualenvs-path: .venv

      - name: Cache dependencies
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-docs-${{ runner.os }}-$${{ matrix.python }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-docs-${{ runner.os }}-${{ matrix.python }}-

      - name: Install dependencies for docs
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --without=dev --without=testing --no-root

      - name: Install root package
        run: poetry install --no-interaction --only-root

      - name: Build and test package documentation
        run: |
          source $VENV
          make docs

      - name: Archive docs artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
          # Artifacts are retained for 90 days by default.
          # In fact, we don't need such long period.
          retention-days: 7
